### PR TITLE
Gagandeep added few codechanges

### PR DESCRIPTION
**Pull request by tgagan7**

### CODE REVIEW

**Review by masystems — COMMENTED** [review]
please remove your name from the file name
please change variable name _ to something more meaningful
please can we change the way that we're taking in the username, password and chrome driver path from a config file that's excluded from commits using a .gitignore file.

**Comment by tgagan7** [comment]
Sure I will do it right away.

**Comment by masystems** [comment]
oh can you also make your commit messages more meaningful too, please.

**Comment by tgagan7** [comment]
I am pushing with new chages 
Added changes:
Exception handling
timed operation for server lag

**Pull request closed without merging**
